### ISSUE TITLE
Нет метода рассчета стоимости доставки calculateprice

### ISSUE THREAD

**Issue by dmitriybaltin** [martinjack/justin#2]
https://justin.ua/api/api_justin_documentation.pdf
Страница 157 документации. Метод calculateprice.
Очевидно метод новый и не был реализован у вас в библиотеки. Скажите, есть ли вероятность, что добавите? Спасибо за ответ.

**Comment by martinjack** [comment]
Добавил

**Comment by dmitriybaltin** [comment]
спасибо большое
